[influxdb]
url = "http://localhost:8086"
db = "glukoz"
retention_policy = "glukoz-rp"
username = "root"
pass = "root"

[downsampler]
measurement_template = "trades_binance_{{id}}_{{time_interval}}"
query_template = """
select price, amount
from glukoz."glukoz-rp".trades_binance_{{id}}_{{time_interval}}
WHERE time >= {{start}} AND time < {{end}}
limit {{limit}}
"""
x_field_index = 0
y_field_index = 1
fields = [
  {name = "timestamp", data_type = "integer"},
  {name = "price", data_type = "float"},
  {name = "amount", data_type = "float"},
]
intervals = [
    "1s",   # 1 point/1  sec       on average
    "5s",   # 1 point/5  sec       on average
    "10s",  # 1 point/10 sec       on average
    "15s",  # 1 point/15 sec       on average
    "30s",  # 1 point/30 sec       on average
    "1m",   # 1 point/1  minute    on average
    "5m",   # 1 point/5  minute    on average
    "10m",  # 1 point/10 minute    on average
    "15m",  # 1 point/15 minute    on average
    "30m",  # 1 point/30 minute    on average
    "1h",   # 1 point/1  hour      on average
    "3h",   # 1 point/3  hour      on average
    "12h",  # 1 point/12 hour      on average
]

[splitter]
measurement_template = "trades_binance_{{id}}_raw"
query_template = """
select price, amount
from glukoz."glukoz-rentention-policy".trade
WHERE feed_id = 'binance'
      AND pair = '{{id}}'
      AND time >= {{start}}
      AND time < {{end}}
      limit {{limit}}
"""
fields = [
  {name = "timestamp", data_type = "integer"},
  {name = "price", data_type = "float"},
  {name = "amount", data_type = "float"},
]

[vars]
ids = [ "ADABNB", "ADABTC", "ADAETH", "ADAUSDT", "ADXBNB", "ADXBTC", "ADXETH", "AEBNB", "AEBTC",
        "AEETH", "AGIBNB", "AGIBTC", "AGIETH", "AIONBNB", "AIONBTC", "AIONETH", "AMBBNB", "AMBBTC",
        "AMBETH", "APPCBNB", "APPCBTC", "APPCETH", "ARDRBNB", "ARDRBTC", "ARDRETH", "ARKBTC",
        "ARKETH", "ARNBTC", "ARNETH", "ASTBTC", "ASTETH", "BATBNB", "BATBTC", "BATETH", "BCCBNB",
        "BCCBTC", "BCCETH", "BCCUSDT", "BCDBTC", "BCDETH", "BCNBNB", "BCNBTC", "BCNETH", "BCPTBNB",
        "BCPTBTC", "BCPTETH", "BLZBNB", "BLZBTC", "BLZETH", "BNBBTC", "BNBETH", "BNBUSDT",
        "BNTBTC", "BNTETH", "BQXBTC", "BQXETH", "BRDBNB", "BRDBTC", "BRDETH", "BTCUSDT", "BTGBTC",
        "BTGETH", "BTSBNB", "BTSBTC", "BTSETH", "CDTBTC", "CDTETH", "CHATBTC", "CHATETH",
        "CLOAKBTC", "CLOAKETH", "CMTBNB", "CMTBTC", "CMTETH", "CNDBNB", "CNDBTC", "CNDETH",
        "CVCBNB", "CVCBTC", "CVCETH", "DASHBTC", "DASHETH", "DATABTC", "DATAETH", "DENTBTC",
        "DENTETH", "DGDBTC", "DGDETH", "DLTBNB", "DLTBTC", "DLTETH", "DNTBTC", "DNTETH", "DOCKBTC",
        "DOCKETH", "EDOBTC", "EDOETH", "ELFBTC", "ELFETH", "ENGBTC", "ENGETH", "ENJBNB", "ENJBTC",
        "ENJETH", "EOSBNB", "EOSBTC", "EOSETH", "EOSUSDT", "ETCBNB", "ETCBTC", "ETCETH", "ETCUSDT",
        "ETHBTC", "ETHUSDT", "EVXBTC", "EVXETH", "FUELBTC", "FUELETH", "FUNBTC", "FUNETH",
        "GASBTC", "GNTBNB", "GNTBTC", "GNTETH", "GOBNB", "GOBTC", "GRSBTC", "GRSETH", "GTOBNB",
        "GTOBTC", "GTOETH", "GVTBTC", "GVTETH", "GXSBTC", "GXSETH", "HCBTC", "HCETH", "HOTBTC",
        "HOTETH", "HSRBTC", "HSRETH", "ICNBTC", "ICNETH", "ICXBNB", "ICXBTC", "ICXETH", "ICXUSDT",
        "INSBTC", "INSETH", "IOSTBTC", "IOSTETH", "IOTABNB", "IOTABTC", "IOTAETH", "IOTAUSDT",
        "IOTXBTC", "IOTXETH", "KEYBTC", "KEYETH", "KMDBTC", "KMDETH", "KNCBTC", "KNCETH",
        "LENDBTC", "LENDETH", "LINKBTC", "LINKETH", "LOOMBNB", "LOOMBTC", "LOOMETH", "LRCBTC",
        "LRCETH", "LSKBNB", "LSKBTC", "LSKETH", "LTCBNB", "LTCBTC", "LTCETH", "LTCUSDT", "LUNBTC",
        "LUNETH", "MANABTC", "MANAETH", "MCOBNB", "MCOBTC", "MCOETH", "MDABTC", "MDAETH", "MFTBNB",
        "MFTBTC", "MFTETH", "MODBTC", "MODETH", "MTHBTC", "MTHETH", "MTLBTC", "MTLETH", "NANOBNB",
        "NANOBTC", "NANOETH", "NASBNB", "NASBTC", "NASETH", "NAVBNB", "NAVBTC", "NAVETH",
        "NCASHBNB", "NCASHBTC", "NCASHETH", "NEBLBNB", "NEBLBTC", "NEBLETH", "NEOBNB", "NEOBTC",
        "NEOETH", "NEOUSDT", "NPXSBTC", "NPXSETH", "NULSBNB", "NULSBTC", "NULSETH", "NULSUSDT",
        "NXSBNB", "NXSBTC", "NXSETH", "OAXBTC", "OAXETH", "OMGBTC", "OMGETH", "ONTBNB", "ONTBTC",
        "ONTETH", "ONTUSDT", "OSTBNB", "OSTBTC", "OSTETH", "PAXBNB", "PAXBTC", "PAXETH", "PAXUSDT",
        "PHXBNB", "PHXBTC", "PHXETH", "PIVXBNB", "PIVXBTC", "PIVXETH", "POABNB", "POABTC",
        "POAETH", "POEBTC", "POEETH", "POLYBNB", "POLYBTC", "POWRBNB", "POWRBTC", "POWRETH",
        "PPTBTC", "PPTETH", "QKCBTC", "QKCETH", "QLCBNB", "QLCBTC", "QLCETH", "QSPBNB", "QSPBTC",
        "QSPETH", "QTUMBNB", "QTUMBTC", "QTUMETH", "QTUMUSDT", "RCNBNB", "RCNBTC", "RCNETH",
        "RDNBNB", "RDNBTC", "RDNETH", "REPBNB", "REPBTC", "REPETH", "REQBTC", "REQETH", "RLCBNB",
        "RLCBTC", "RLCETH", "RPXBNB", "RPXBTC", "RPXETH", "RVNBNB", "RVNBTC", "SALTBTC", "SALTETH",
        "SCBNB", "SCBTC", "SCETH", "SKYBNB", "SKYBTC", "SKYETH", "SNGLSBTC", "SNGLSETH", "SNMBTC",
        "SNMETH", "SNTBTC", "SNTETH", "STEEMBNB", "STEEMBTC", "STEEMETH", "STORJBTC", "STORJETH",
        "STORMBNB", "STORMBTC", "STORMETH", "STRATBTC", "STRATETH", "SUBBTC", "SUBETH", "SYSBNB",
        "SYSBTC", "SYSETH", "THETABNB", "THETABTC", "THETAETH", "TNBBTC", "TNBETH", "TNTBTC",
        "TNTETH", "TRIGBNB", "TRIGBTC", "TRIGETH", "TRXBNB", "TRXBTC", "TRXETH", "TRXUSDT",
        "TUSDBNB", "TUSDBTC", "TUSDETH", "TUSDUSDT", "VENBNB", "VENBTC", "VENETH", "VENUSDT",
        "VETBNB", "VETBTC", "VETETH", "VETUSDT", "VIABNB", "VIABTC", "VIAETH", "VIBBTC", "VIBEBTC",
        "VIBEETH", "VIBETH", "WABIBNB", "WABIBTC", "WABIETH", "WANBNB", "WANBTC", "WANETH",
        "WAVESBNB", "WAVESBTC", "WAVESETH", "WINGSBTC", "WINGSETH", "WPRBTC", "WPRETH", "WTCBNB",
        "WTCBTC", "WTCETH", "XEMBNB", "XEMBTC", "XEMETH", "XLMBNB", "XLMBTC", "XLMETH", "XLMUSDT",
        "XMRBTC", "XMRETH", "XRPBNB", "XRPBTC", "XRPETH", "XRPUSDT", "XVGBTC", "XVGETH", "XZCBNB",
        "XZCBTC", "XZCETH", "YOYOBNB", "YOYOBTC", "YOYOETH", "ZECBTC", "ZECETH", "ZENBNB",
        "ZENBTC", "ZENETH", "ZILBNB", "ZILBTC", "ZILETH", "ZRXBTC", "ZRXETH"]