[influxdb]
url = "http://localhost:8086"
db = "glukoz"
retention_policy = "glukoz-rp"
username = "root"
pass = "root"

[downsampler]
measurement_template = "trades_binance_{{id}}_{{time_interval}}"
query_template = """
select price, amount
from glukoz."glukoz-rp".trades_binance_{{id}}_{{time_interval}}
WHERE time >= {{start}} AND time < {{end}}
limit {{limit}}
"""
x_field_index = 0
y_field_index = 1
fields = [
  {name = "timestamp", data_type = "integer"},
  {name = "price", data_type = "float"},
  {name = "amount", data_type = "float"},
]
intervals = [
    "1s",   # 1 point/1  sec       on average
    "1m",   # 1 point/1  minute    on average
    "5m",   # 1 point/5  minute    on average
    "10m",  # 1 point/10 minute    on average
    "15m",  # 1 point/15 minute    on average
    "30m",  # 1 point/30 minute    on average
    "1h",   # 1 point/1  hour      on average
    "3h",   # 1 point/3  hour      on average
    "12h",  # 1 point/12 hour      on average
]

[splitter]
measurement_template = "trades_binance_{{id}}_raw"
query_template = """
select price, amount
from glukoz."glukoz-rentention-policy".trade
WHERE feed_id = 'binance'
      AND pair = '{{id}}'
      AND time >= {{start}}
      AND time < {{end}}
      limit {{limit}}
"""
fields = [
  {name = "timestamp", data_type = "integer"},
  {name = "price", data_type = "float"},
  {name = "amount", data_type = "float"},
]

[vars]
ids = [ "QSPBNB", "HOTBTC", "POEBTC", "XMRETH", "PHXBTC", "STORMBTC", "SCBNB", "ONTETH", "AEBNB",
        "KMDBTC", "STEEMBTC", "NCASHBTC", "XLMETH", "NXSBNB", "STEEMETH", "OSTBNB", "ZILBTC",
        "OSTETH", "LSKBNB", "POWRBTC", "DATAETH", "RLCBTC", "CVCETH", "VENUSDT", "AMBETH",
        "WABIBTC", "VETBTC", "TNTETH", "WINGSETH", "NPXSBTC", "THETAETH", "NCASHBNB", "PIVXETH",
        "DASHETH", "MFTBTC", "MDABTC", "PPTBTC", "REQBTC", "TUSDUSDT", "XRPBNB", "RDNBTC",
        "XLMUSDT", "TRIGETH", "RDNBNB", "NEBLBTC", "LSKETH", "MANABTC", "QLCETH", "STRATBTC",
        "MDAETH", "AGIETH", "DLTETH", "POEETH", "WANETH", "VIBETH", "IOTXBTC", "KMDETH", "SNTBTC",
        "VIBEETH", "IOSTBTC", "SUBBTC", "BCPTETH", "IOTABTC", "ARNETH", "ENGETH", "OMGETH",
        "XLMBTC", "NULSUSDT", "STORMBNB", "CHATBTC", "ASTBTC", "TUSDBNB", "GVTETH", "MFTBNB",
        "DOCKETH", "RCNBTC", "PIVXBTC", "KEYETH", "CMTBNB", "SKYETH", "ZENETH", "REPBNB",
        "ARDRETH", "BLZBNB", "LOOMBNB", "ENJBTC", "NXSETH", "XVGETH", "SCETH", "BLZETH", "BCPTBTC",
        "MTHETH", "ETCUSDT", "GNTETH", "IOTABNB", "ELFBTC", "LUNBTC", "DENTETH", "BCCBTC",
        "SALTBTC", "SYSBTC", "EOSBNB", "TRXUSDT", "YOYOBNB", "MCOBNB", "TNTBTC", "BQXBTC",
        "VENBNB", "QKCETH", "REPBTC", "BRDBNB", "GRSETH", "ZECETH", "QTUMUSDT", "ENJBNB",
        "AIONBTC", "VIAETH", "VIBBTC", "XLMBNB", "RLCETH", "PHXBNB", "ONTBNB", "ZRXETH", "TNBBTC",
        "ARDRBNB", "NPXSETH", "POWRETH", "CLOAKBTC", "CLOAKETH", "XEMBTC", "NASETH", "ICXUSDT",
        "TUSDETH", "STORJBTC", "NEBLETH", "ZILETH", "RCNETH", "TRXBNB", "PAXUSDT", "QSPETH",
        "STRATETH", "ARDRBTC", "ADXBNB", "QTUMBNB", "SNMBTC", "BCCUSDT", "BCNBTC", "POLYBTC",
        "ZECBTC", "ADXETH", "DGDBTC", "LTCBTC", "WTCETH", "QTUMBTC", "SNGLSBTC", "PAXBNB",
        "XMRBTC", "THETABNB", "VIABTC", "STEEMBNB", "ZENBNB", "BTCUSDT", "WABIBNB", "BATETH",
        "VIABNB", "VETUSDT", "EVXETH", "CNDBTC", "BCCBNB", "EOSBTC", "ICXETH", "LUNETH", "LTCUSDT",
        "BCDBTC", "INSETH", "ETHUSDT", "MCOBTC", "GXSETH", "CNDBNB", "NANOETH", "AEBTC", "CVCBTC",
        "ONTUSDT", "ICXBTC", "NEOBTC", "SKYBTC", "NAVBTC", "ADABTC", "LTCETH", "TRXBTC", "VETBNB",
        "BATBTC", "GTOBNB", "NEOETH", "WPRBTC", "SKYBNB", "MODETH", "IOTAETH", "XEMBNB", "OMGBTC",
        "DNTETH", "NULSBNB", "PPTETH", "RPXBTC", "KNCBTC", "IOTXETH", "WTCBNB", "TRIGBTC",
        "WAVESBTC", "WAVESBNB", "FUNBTC", "BNBUSDT", "RCNBNB", "TNBETH", "BNTETH", "XZCBNB",
        "ETHBTC", "GNTBTC", "CMTETH", "POLYBNB", "ONTBTC", "XRPUSDT", "REPETH", "AGIBTC", "WTCBTC",
        "BTSETH", "BTGETH", "MODBTC", "POWRBNB", "RPXBNB", "SYSBNB", "EDOETH", "GTOETH", "KNCETH",
        "CVCBNB", "ZRXBTC", "SYSETH", "MANAETH", "WAVESETH", "APPCBTC", "CMTBTC", "RDNETH",
        "CNDETH", "OAXBTC", "FUNETH", "SNTETH", "ETCETH", "WANBTC", "AGIBNB", "GOBTC", "XZCBTC",
        "ICNETH", "RLCBNB", "NANOBNB", "QKCBTC", "LENDETH", "YOYOETH", "NULSBTC", "PAXBTC",
        "POAETH", "QSPBTC", "THETABTC", "GXSBTC", "NEBLBNB", "LOOMBTC", "MFTETH", "BTSBNB",
        "LRCETH", "EOSETH", "GOBNB", "NXSBTC", "ARKBTC", "HSRBTC", "WANBNB", "LRCBTC", "ADAETH",
        "BCNBNB", "NULSETH", "BNBETH", "FUELBTC", "OAXETH", "XVGBTC", "CDTETH", "TRIGBNB",
        "LINKBTC", "BQXETH", "MTHBTC", "ADAUSDT", "WINGSBTC", "YOYOBTC", "PAXETH", "DLTBNB",
        "LTCBNB", "DATABTC", "BRDETH", "NAVETH", "MTLBTC", "ZILBNB", "RVNBNB", "LSKBTC", "TRXETH",
        "REQETH", "HCBTC", "ARKETH", "POABNB", "LENDBTC", "ELFETH", "QTUMETH", "BCCETH", "BTSBTC",
        "QLCBNB", "STORJETH", "NANOBTC", "NASBTC", "NASBNB", "CHATETH", "AMBBTC", "HCETH",
        "ICNBTC", "VIBEBTC", "MCOETH", "EOSUSDT", "INSBTC", "BCDETH", "BRDBTC", "BLZBTC", "GTOBTC",
        "BNTBTC", "AMBBNB", "KEYBTC", "AEETH", "ENJETH", "PIVXBNB", "XZCETH", "RVNBTC", "NEOBNB",
        "SALTETH", "ETCBNB", "ARNBTC", "VENETH", "OSTBTC", "SNGLSETH", "ETCBTC", "BCPTBNB",
        "SUBETH", "ADXBTC", "WABIETH", "CDTBTC", "WPRETH", "GVTBTC", "GRSBTC", "LOOMETH", "VENBTC",
        "ADABNB", "LINKETH", "BCNETH", "NCASHETH", "ICXBNB", "EDOBTC", "HSRETH", "POABTC",
        "ZENBTC", "NEOUSDT", "BNBBTC", "DGDETH", "SCBTC", "XEMETH", "TUSDBTC", "APPCBNB",
        "AIONETH", "RPXETH", "PHXETH", "GNTBNB", "MTLETH", "FUELETH", "HOTETH", "EVXBTC",
        "DASHBTC", "XRPETH", "GASBTC", "ENGBTC", "DOCKBTC", "XRPBTC", "STORMETH", "DLTBTC",
        "DENTBTC", "BATBNB", "NAVBNB", "IOSTETH", "AIONBNB", "SNMETH", "DNTBTC", "APPCETH",
        "QLCBTC", "ASTETH", "BTGBTC", "VETETH", "IOTAUSDT",]